// ===== EMAIL SERVICE =====
// Sends email via Nodemailer using SMTP settings from .env.
// If no SMTP is configured (development), it logs the email to the console
// instead so the app is fully testable without any real email provider.
//
// .env options:
//   SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, MAIL_FROM
//   APP_URL   -> base URL used to build reset links (default http://localhost:5000)

const nodemailer = require("nodemailer");

const FROM = process.env.MAIL_FROM || `"Complaint Management System" <${process.env.SMTP_USER || "no-reply@localhost"}>`;
const APP_URL = process.env.APP_URL || "http://localhost:5000";

const isConfigured = () => Boolean(process.env.SMTP_HOST);

let transporter = null;
if (isConfigured()) {
  transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: parseInt(process.env.SMTP_PORT, 10) || 587,
    secure: (process.env.SMTP_PORT || "587") === "465",
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });
}

// logEmail is the development fallback: prints the message instead of sending.
function logEmail(to, subject, html) {
  console.log("\n============================================");
  console.log(`[DEV EMAIL] To: ${to}`);
  console.log(`Subject: ${subject}`);
  console.log("--------------------------------------------");
  console.log(html.replace(/<[^>]+>/g, " ").replace(/  +/g, " ").trim());
  console.log("============================================\n");
}

// sendEmail(to, subject, html) -> always resolves; never throws to the caller.
async function sendEmail(to, subject, html) {
  try {
    if (!to) return;
    if (!isConfigured() || !transporter) {
      logEmail(to, subject, html);
      return { delivered: false, dev: true };
    }
    const info = await transporter.sendMail({ from: FROM, to, subject, html });
    return { delivered: true, dev: false, messageId: info.messageId };
  } catch (err) {
    console.error("Email send error:", err.message);
    return { delivered: false, error: err.message };
  }
}

// Standard base layout wrapper for simple HTML emails.
function wrap(body) {
  return `
    <div style="font-family:Arial,Helvetica,sans-serif;max-width:560px;margin:auto;border:1px solid #e5e7eb;border-radius:10px;overflow:hidden;">
      <div style="background:#2563eb;color:#fff;padding:16px 24px;font-size:18px;font-weight:700;">📋 Complaint Management System</div>
      <div style="padding:24px;color:#1f2937;font-size:15px;line-height:1.6;">${body}</div>
      <div style="background:#f9fafb;border-top:1px solid #e5e7eb;padding:14px 24px;color:#6b7280;font-size:13px;">
        Generated by Complaint Management System · ${APP_URL}
      </div>
    </div>
  `;
}

module.exports = {
  sendEmail,
  wrap,
  APP_URL,
  isConfigured,
};
